// <auto-generated />
using BusinessLogic.Classes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessLogic.Migrations
{
    [DbContext(typeof(MmoContext))]
    [Migration("20251113140131_BossUpdateItemDropInit")]
    partial class BossUpdateItemDropInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("BossItemDrop", b =>
                {
                    b.Property<int>("BossesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemDropsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BossesId", "ItemDropsID");

                    b.HasIndex("ItemDropsID");

                    b.ToTable("BossItemDrop");
                });

            modelBuilder.Entity("BusinessLogic.Classes.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLife")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("BusinessLogic.Classes.ItemDrop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("ItemDrops");
                });

            modelBuilder.Entity("BusinessLogic.Classes.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BossId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("BusinessLogic.Classes.MmoPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Roleclass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MmoPlayers");
                });

            modelBuilder.Entity("BossItemDrop", b =>
                {
                    b.HasOne("BusinessLogic.Classes.Boss", null)
                        .WithMany()
                        .HasForeignKey("BossesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Classes.ItemDrop", null)
                        .WithMany()
                        .HasForeignKey("ItemDropsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Classes.ItemDrop", b =>
                {
                    b.OwnsOne("BusinessLogic.Classes.StatInfo", "ClassStat", b1 =>
                        {
                            b1.Property<int>("ItemDropID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StatName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("StatValue")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ItemDropID");

                            b1.ToTable("ItemDrops");

                            b1.WithOwner()
                                .HasForeignKey("ItemDropID");
                        });

                    b.OwnsOne("BusinessLogic.Classes.StatInfo", "PrimaryStat", b1 =>
                        {
                            b1.Property<int>("ItemDropID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StatName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("StatValue")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ItemDropID");

                            b1.ToTable("ItemDrops");

                            b1.WithOwner()
                                .HasForeignKey("ItemDropID");
                        });

                    b.OwnsOne("BusinessLogic.Classes.StatInfo", "SecondaryStat", b1 =>
                        {
                            b1.Property<int>("ItemDropID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StatName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("StatValue")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ItemDropID");

                            b1.ToTable("ItemDrops");

                            b1.WithOwner()
                                .HasForeignKey("ItemDropID");
                        });

                    b.OwnsOne("BusinessLogic.Classes.StatInfo", "TertiaryStat", b1 =>
                        {
                            b1.Property<int>("ItemDropID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StatName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("StatValue")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ItemDropID");

                            b1.ToTable("ItemDrops");

                            b1.WithOwner()
                                .HasForeignKey("ItemDropID");
                        });

                    b.Navigation("ClassStat")
                        .IsRequired();

                    b.Navigation("PrimaryStat")
                        .IsRequired();

                    b.Navigation("SecondaryStat")
                        .IsRequired();

                    b.Navigation("TertiaryStat");
                });

            modelBuilder.Entity("BusinessLogic.Classes.Mechanic", b =>
                {
                    b.HasOne("BusinessLogic.Classes.Boss", "Boss")
                        .WithMany("Mechanics")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boss");
                });

            modelBuilder.Entity("BusinessLogic.Classes.Boss", b =>
                {
                    b.Navigation("Mechanics");
                });
#pragma warning restore 612, 618
        }
    }
}
