name: Test suite runner
run-name: Test trial of ${{ github.actor }}

on:
  push:
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-test:
    name: build-and-test-windows-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Dependencies
        working-directory: MMOlogs_BackEnd
        run: dotnet restore

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"JansenBhodi_BackEnd_MMOlogs" /o:"jansenbhodi" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml" /d:sonar.coverage.exclusions="**/Migrations/**,**/obj/**,**/bin/**,**/Classes/**,**/DTO/**,**/Repository/**,**/Program.cs,**/WeatherForecast.cs,**/MSTestSettings.cs,**/Test1.cs"

      - name: Build
        run: dotnet build MMOlogs_BackEnd/MMOlogs_BackEnd.csproj --configuration Release

      - name: Test with coverage
        run: dotnet-coverage collect "dotnet test BackEnd_Testing/BackEnd_Testing.csproj --verbosity normal" -f xml -o ${{ github.workspace }}/coverage.xml

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"